### ISSUE TITLE
Can deepEdit detect the most confidence site in the region?

### ISSUE THREAD

**Issue by JeremyQuo** [weir12/DeepEdit#15]
There is a special bed file that required by DeepEdit.
I want  to know if I can input a bed annotated some region.
And deepedit told me the most confidence sites.
Many thanks if can help

**Comment by JeremyQuo** [comment]
If not, we need to extract all A bases on our reference and build a site level bed to see all the prediction on it?

**Comment by weir12** [comment]
Dear JeremyQuo,

Thank you for your interest in DeepEdit and for reaching out to our team. We appreciate your attention to our work. However, we regret to inform you that the current version of DeepEdit does not support the direct input of a BED file annotated with specific regions or provide predictions for those regions.

Thank you for your understanding, and we wish you success in your research.

Best regards,
Ou Liang

**Comment by JeremyQuo** [comment]
Thanks for your reply
