### ISSUE TITLE
please tell me more details about the labels

### ISSUE THREAD

**Issue by LuckyMLucy** [weir12/DeepEdit#17]
Dear Developer,
I am Menglu. My supervisor and I are conducting identification studies of RNA modifications
I am very interested in your project and am trying to reproduce your model. But for the training data, I don't know exactly how to get the label of the data, whether it is a 0-1 variable (indicating whether there is a modification or not) or a continuous variable (representing the modified ratio). This is very important for our work afterwards, if so, can it be reproduced with the data from which you trained the model (csv data with label). We hope to have the opportunity to further communicate and cooperate with you. Looking forward to your response.

**Comment by LongxianChen** [comment]
Hi, Menglu,
I have replied your email. You can check the answer there.

**Comment by LuckyMLucy** [comment]
@LongxianChen I am sorry, There may be something wrong so I am not currently receiving a response from you. Can you tell me here or send to: MengluChan@hotmail.com?

**Comment by LuckyMLucy** [comment]
OK, thanks a lot !
