### ISSUE TITLE
Model for human

### ISSUE THREAD

**Issue by cavei** [weir12/DeepEdit#18]
Can you provide the model for human, I mean a "S.pombe_model.h5" for human.
Or do I use S.pombe_model also for human?

I've seen also your https://www.zenodo.org/record/7615493.
Can you tell which is the human h5?

Thanks for your help.
Best Regards

**Comment by LongxianChen** [comment]
Hi,
You can use the S.pombe_model.h5 model for human directly.
Please note it is currently challenging for DeepEdit to predict RNA editings located in untrained motif contexts. Please check whether the motifs of the sites you are interested in have been trained in our provided model. The trained motifs were listed in the Trained_motifs_v1.0.txt file in DeepEdit/Docs folder.
Best Regards

**Comment by cavei** [comment]
Hi, thanks for your reply.
Best
